name: Build-Image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest
      env:
        DOCKER_HOST: tcp://docker-in-docker:2375
      networks:
        - dind
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: git.erwine.dev/mason/osu-uwrt:dev-container