steps:
  build-and-publish:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [ docker-api-key ]
    settings:
      buildkit_driveropt: "network=host"
      repo: mason/osu-uwrt-devcontainer
      tag: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: docker-api-key
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event:
        - push
        - manual
