steps:
  build-and-publish:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [ git-api-key ]
    environment:
      NODE_IP:
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      DOCKER_HOST: tcp://192.168.1.7:2375
    settings:
      repo: ${CI_REPO}
      tag: devcontainer
      registry: git.erwine.dev
      username: ${CI_REPO_OWNER}
      password:
        from_secret: git-api-key
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push