steps:
  build-and-publish:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [ git-api-key ]
    settings:
      buildkit_driveropt: "network=host"
      repo: ${CI_REPO}
      tag: latest
      registry: https://git.erwine.dev
      cache_images: git.erwine.dev/mason/osu-uwrt-devcontainer:latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: git-api-key
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event:
        - push
        - manual
